project:
  type: website
  output-dir: docs

website:
  title: "My Portfolio"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: portfolio.qmd
        text: Demographic Change Analyses

      - href: cv.qmd
        text: CV

# format:
#   htm
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true
# 
# editor: visual